# name of the workflow
name: build

# event = workflow will be trigger when new push on branch main
on:
  push:
    branches:
      - 'main'  

# global env
env:
  DOCKERHUB_USERNAME: yukanyan

# job
jobs:
  docker:
    # env to run
    runs-on: ubuntu-latest
    steps:
        # 1. checkout code
      - name: Checkout
        uses: actions/checkout@v3
        # 2. export env sha_short, values is short commit id
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
        # 3. setup Docker buildx
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        # 4. Docker login
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        # 5. build & push
      - name: Build backend and push
        uses: docker/build-push-action@v3
        with:
          context: backend
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/backend:${{ steps.vars.outputs.sha_short }}
      - name: Build frontend and push
        uses: docker/build-push-action@v3
        with:
          context: frontend
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/frontend:${{ steps.vars.outputs.sha_short }}
